# Model configuration for transformer-based PPO agent
observation_dim: 31  # Feature dimension per board position
observation_length: 16  # Board size (sequence length)
action_dim: 4  # up, down, left, right
hidden_dim: 512
d_model: 256
nhead: 8
num_layers: 4
dim_feedforward: 1024
dropout: 0.1
reduction: "mean"  # Transformer output reduction method: "mean" or "cls"
