# path to working directory
work_dir: ${hydra:runtime.cwd}

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${paths.work_dir}/../results/
