# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: default
  - model: transformer_combined
  - trainer: default
  - paths: default
  - hydra: default

# task name, determines output directory path
task_name: "train_transformer_combined"

# seed for random number generators in pytorch, numpy and python.random
seed: null
